# Generated by Django 5.0.1 on 2024-01-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributename',
            name='nazev',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attributename',
            name='zobrazit',
            field=models.BooleanField(default=True),
        ),
    ]
