# Generated by Django 5.0.1 on 2024-01-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_attributename_zobrazit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributename',
            name='kod',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
