# Generated by Django 5.0.1 on 2024-01-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_attributename_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='obrazek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.image'),
        ),
    ]
